all: dfe_generator dfe_generator_isc

dfe_generator: dfe_generator.cpp
	$(CXX) -o dfe_generator dfe_generator.cpp

dfe_generator_isc: dfe_generator_isc.cpp
	$(CXX) -o dfe_generator_isc dfe_generator_isc.cpp
